#!/usr/bin/env python

#used to find sum of the values of keys generated by mapper

import sys

currkey = None

total = 0
for input_line in sys.stdin:
	input_line = input_line.strip()
	prevkey, value = input_line.split("\t", 1)
	value = int(value)
	if currkey == prevkey:
		total += value
	else:
		if currkey:
			print( "%s\t%d" % (currkey, total) )
		total = value
		currkey = prevkey

if currkey == prevkey:
	print( "%s\t%d" % (currkey, total) )
